<?php

require_once('classes/Jail.php');
require_once('classes/Network.php');
require_once('classes/NetworkDevice.php');
require_once('classes/Service.php');
require_once('classes/Mount.php');

/**
 * Implements hook_permission().
 */
function jailadmin_permission() {
    $jails = Jail::LoadAll();

    $perms = array(
        'administer jails' => array(
            'title' => t('Administer Wayfair Jail Admin'),
        ),
        'start jails' => array(
            'title' => t('Start/Stop jails'),
        ),
        'view jails' => array(
            'title' => t('View jails'),
        ),
    );

    foreach ($jails as $jail) {
        $perms['config ' . $jail->name] = array(
            'title' => t('Configure jail @jail', array('@jail' => $jail->name))
        );

        $perms['view ' . $jail->name . ' config'] = array(
            'title' => t('View @jail\'s config', array('@jail' => $jail->name))
        );
    }

    return $perms;
}

function jailadmin_menu() {
    /* Admin settings */
    $items['admin/config/jailadmin'] = array(
        'title' => 'Wayfair Jail Admin',
        'description' => 'Wayfair Jail Admin settings',
        'position' => 'right',
        'weight' => -5,
        'page callback' => 'system_admin_menu_block_page',
        'access arguments' => array('administer jails'),
        'file' => 'system.admin.inc',
        'file path' => drupal_get_path('module', 'system'),
    );

    $items['admin/config/jailadmin/settings'] = array(
        'title' => 'Wayfair Jail Admin Settings',
        'description' => 'Settings for Wayfair Jail Admin',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('jailadmin_admin_settings'),
        'access arguments' => array('administer jails'),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'jailadmin.admin.inc',
    );

    $items['admin/config/jailadmin/networks'] = array(
        'title' => 'Wayfair Jail Networks',
        'description' => 'Networks for Jails',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('jailadmin_admin_settings_network'),
        'access arguments' => array('administer jails'),
        'type' => MENU_NORMAL_ITEM,
        'file' => 'jailadmin.admin.inc',
    );

    /* Actions */
    $items['jailadmin/status'] = array(
        'title' => 'Jail Status',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('jailadmin_status'),
        'file' => 'jailstatus.inc',
        'access callback' => 'user_access',
        'access arguments' => array('view jails'),
        'type' => MENU_NORMAL_ITEM,
    );

    $items['jailadmin/%/config'] = array(
        'title' => 'Configure Jail',
        'page callback' => 'drupal_get_form',
        'page arguments' => array('jailadmin_config', 1),
        'file' => 'jailconfig.inc',
        'access callback' => 'jail_config_access',
        'access arguments' => array(1),
        'type' => MENU_NORMAL_ITEM,
    );

    return $items;
}

function jail_config_access($jail) {
    if (user_access('view ' . $jail . ' config') || user_access('config ' . $jail))
        return TRUE;

    return FALSE;
}
